# Generated by Django 4.2.4 on 2023-09-07 13:46

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('model', models.TextField()),
                ('range', models.IntegerField()),
            ],
            options={
                'db_table': 'aircrafts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(primary_key=True, serialize=False)),
                ('airport_name', models.TextField()),
                ('city', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('timezone', models.TextField()),
            ],
            options={
                'db_table': 'airports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_ref', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('book_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(primary_key=True, serialize=False)),
                ('flight_no', models.CharField(max_length=6)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('actual_departure', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField()),
            ],
            options={
                'db_table': 'flights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_no', models.CharField(primary_key=True, serialize=False)),
                ('fare_conditions', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'seats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.CharField(primary_key=True, serialize=False)),
                ('passenger_id', models.CharField(max_length=20)),
                ('contact_data', jsonfield.fields.JSONField()),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('ticket_no', models.ForeignKey(db_column='ticket_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aviaweb.ticket')),
                ('boarding_no', models.IntegerField()),
                ('seat_no', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'boarding_passes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketFlight',
            fields=[
                ('ticket_no', models.ForeignKey(db_column='ticket_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aviaweb.ticket')),
                ('flight_id', models.IntegerField()),
                ('fare_conditions', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ticket_flights',
                'managed': False,
            },
        ),
    ]
